We need to explicitly install python3.8-distutils
Otherwise we get the error "ImportError: cannot import name 'dist'".

https://stackoverflow.com/a/62813917/648162